window.quizMovies = [
  { id: 'matrix', title: 'The Matrix', year: 1999, genre: 'Ciencia ficción', color: 'linear-gradient(145deg,#103d3b,#0b181c 78%)', facts: [
    ['pastilla','¿De qué color es la pastilla que elige Neo?','Roja',['Roja','Azul','Verde','Blanca']],
    ['actor','¿Quién interpreta a Neo?','Keanu Reeves',['Keanu Reeves','Brad Pitt','Tom Cruise','Christian Bale']],
    ['mentor','¿Cómo se llama el mentor de Neo?','Morpheus',['Morpheus','Cypher','Tank','Mouse']],
    ['heroína','¿Quién interpreta a Trinity?','Carrie-Anne Moss',['Carrie-Anne Moss','Sandra Bullock','Charlize Theron','Milla Jovovich']],
    ['agente','¿Qué apellido tiene el agente que persigue a Neo?','Smith',['Smith','Jones','Brown','Anderson']],
    ['nave','¿Cómo se llama la nave de Morpheus?','Nabucodonosor',['Nabucodonosor','Ícaro','Prometheus','Nostromo']],
    ['ciudad','¿Cómo se llama la última ciudad humana?','Zion',['Zion','Sion Prime','Arcadia','Eden']],
    ['tatuaje','¿Qué animal aparece en el tatuaje que Neo debe seguir?','Un conejo blanco',['Un conejo blanco','Un gato negro','Una mariposa','Una serpiente']],
    ['trabajo','¿Cuál es el trabajo de Thomas Anderson antes de despertar?','Programador',['Programador','Periodista','Policía','Arquitecto']],
    ['oraculo','¿Quién le habla a Neo sobre su destino?','El Oráculo',['El Oráculo','El Arquitecto','El Cerrajero','El Merovingio']],
    ['codigo','¿De qué color se ve el código de Matrix?','Verde',['Verde','Rojo','Azul','Dorado']],
    ['direccion','¿Quiénes dirigieron la película?','Lana y Lilly Wachowski',['Lana y Lilly Wachowski','Los hermanos Russo','Joel y Ethan Coen','Peter y Bobby Farrelly']]
  ]},
  { id: 'titanic', title: 'Titanic', year: 1997, genre: 'Drama', color: 'linear-gradient(145deg,#315b79,#121b29 78%)', facts: [
    ['actor','¿Quién interpreta a Jack Dawson?','Leonardo DiCaprio',['Leonardo DiCaprio','Matt Damon','Brad Pitt','Johnny Depp']],
    ['actriz','¿Quién interpreta a Rose?','Kate Winslet',['Kate Winslet','Nicole Kidman','Julia Roberts','Sandra Bullock']],
    ['iceberg','¿Contra qué choca el barco?','Un iceberg',['Un iceberg','Otro barco','Un arrecife','Una mina']],
    ['joya','¿Cómo se llama el collar azul?','El Corazón del Océano',['El Corazón del Océano','La Estrella del Atlántico','El Diamante Real','La Lágrima de Poseidón']],
    ['año','¿En qué año se hunde el Titanic?','1912',['1912','1905','1920','1931']],
    ['destino','¿A qué ciudad se dirigía el barco?','Nueva York',['Nueva York','Boston','Londres','París']],
    ['salida','¿Desde qué puerto inicia su viaje?','Southampton',['Southampton','Liverpool','Belfast','Dublín']],
    ['dibujo','¿Qué le pide Rose a Jack que dibuje?','Un retrato de ella',['Un retrato de ella','El barco','El collar','Un paisaje']],
    ['director','¿Quién dirigió Titanic?','James Cameron',['James Cameron','Steven Spielberg','Ridley Scott','Ron Howard']],
    ['prometido','¿Cómo se llama el prometido de Rose?','Cal',['Cal','Bill','James','Thomas']],
    ['musica','¿Quién canta My Heart Will Go On?','Céline Dion',['Céline Dion','Whitney Houston','Mariah Carey','Barbra Streisand']],
    ['oceano','¿En qué océano ocurre el naufragio?','Atlántico Norte',['Atlántico Norte','Pacífico Sur','Índico','Ártico']]
  ]},
  { id: 'backfuture', title: 'Volver al Futuro', year: 1985, genre: 'Aventura', color: 'linear-gradient(145deg,#614e93,#191426 78%)', facts: [
    ['auto','¿Qué auto se convierte en máquina del tiempo?','DeLorean',['DeLorean','Mustang','Camaro','Porsche']],
    ['velocidad','¿Qué velocidad debe alcanzar el DeLorean?','88 millas por hora',['88 millas por hora','100 millas por hora','77 millas por hora','55 millas por hora']],
    ['cientifico','¿Cómo llaman al científico Emmett Brown?','Doc',['Doc','Profesor','Brownie','Einstein']],
    ['año','¿A qué año viaja Marty por accidente?','1955',['1955','1965','1975','1995']],
    ['actor','¿Quién interpreta a Marty McFly?','Michael J. Fox',['Michael J. Fox','Tom Cruise','Rob Lowe','Matthew Broderick']],
    ['invento','¿Qué dispositivo hace posible el viaje en el tiempo?','El condensador de flujo',['El condensador de flujo','El reactor cuántico','La cámara temporal','El núcleo de plasma']],
    ['villano','¿Quién acosa a George McFly?','Biff Tannen',['Biff Tannen','Griff Wilson','Needles','Strickland']],
    ['madre','¿Cómo se llama la madre de Marty?','Lorraine',['Lorraine','Jennifer','Clara','Linda']],
    ['padre','¿Cómo se llama el padre de Marty?','George',['George','Dave','Emmett','Calvin']],
    ['rayo','¿Qué energía permite el regreso a 1985?','Un rayo',['Un rayo','Un terremoto','Un tornado','Un eclipse']],
    ['torre','¿Dónde debe caer el rayo?','En la torre del reloj',['En la torre del reloj','En la escuela','En el puente','En la casa de Doc']],
    ['director','¿Quién dirigió la película?','Robert Zemeckis',['Robert Zemeckis','Steven Spielberg','John Hughes','Joe Dante']]
  ]},
  { id: 'harrypotter', title: 'Harry Potter', year: 2001, genre: 'Fantasía', color: 'linear-gradient(145deg,#5c4b2f,#181611 78%)', facts: [
    ['escuela','¿Cómo se llama la escuela de magia?','Hogwarts',['Hogwarts','Beauxbatons','Durmstrang','Ilvermorny']],
    ['casa','¿A qué casa pertenece Harry?','Gryffindor',['Gryffindor','Slytherin','Ravenclaw','Hufflepuff']],
    ['buho','¿Cómo se llama la lechuza de Harry?','Hedwig',['Hedwig','Errol','Pigwidgeon','Fawkes']],
    ['anden','¿Desde qué andén sale el Expreso de Hogwarts?','9¾',['9¾','7½','10¼','13']],
    ['deporte','¿Qué deporte se juega volando en escobas?','Quidditch',['Quidditch','Gobstones','Cricket mágico','Quodpot']],
    ['enemigo','¿Qué mago oscuro intenta matar a Harry?','Voldemort',['Voldemort','Grindelwald','Lucius Malfoy','Snape']],
    ['amigos','¿Quiénes son los dos mejores amigos de Harry?','Ron y Hermione',['Ron y Hermione','Fred y George','Neville y Luna','Draco y Pansy']],
    ['director','¿Quién dirige Hogwarts durante la mayor parte de la saga?','Albus Dumbledore',['Albus Dumbledore','Severus Snape','Minerva McGonagall','Sirius Black']],
    ['actor','¿Quién interpreta a Harry?','Daniel Radcliffe',['Daniel Radcliffe','Rupert Grint','Tom Felton','Robert Pattinson']],
    ['varitas','¿Cómo se llama la tienda de varitas?','Ollivanders',['Ollivanders','Flourish y Blotts','Honeydukes','Borgin y Burkes']],
    ['patronus','¿Qué forma tiene el Patronus de Harry?','Un ciervo',['Un ciervo','Un lobo','Una nutria','Un fénix']],
    ['objeto','¿Qué objeto decide la casa de cada alumno?','El Sombrero Seleccionador',['El Sombrero Seleccionador','El Cáliz de Fuego','El Espejo de Oesed','La Piedra Filosofal']]
  ]},
  { id: 'jurassic', title: 'Jurassic Park', year: 1993, genre: 'Aventura', color: 'linear-gradient(145deg,#4b6437,#131a12 78%)', facts: [
    ['isla','¿Cómo se llama la isla del parque?','Isla Nublar',['Isla Nublar','Isla Sorna','Isla Muerta','Isla Calavera']],
    ['creador','¿Quién crea el parque?','John Hammond',['John Hammond','Alan Grant','Ian Malcolm','Henry Wu']],
    ['director','¿Quién dirigió la película?','Steven Spielberg',['Steven Spielberg','James Cameron','George Lucas','Robert Zemeckis']],
    ['paleontologo','¿Cómo se llama el paleontólogo protagonista?','Alan Grant',['Alan Grant','Ian Malcolm','Robert Muldoon','Dennis Nedry']],
    ['adn','¿En qué insecto encuentran ADN de dinosaurio?','Un mosquito',['Un mosquito','Una abeja','Una hormiga','Una libélula']],
    ['ambar','¿Dónde quedó atrapado el insecto?','En ámbar',['En ámbar','En hielo','En resina sintética','En una roca']],
    ['saboteador','¿Quién sabotea la seguridad del parque?','Dennis Nedry',['Dennis Nedry','Henry Wu','Donald Gennaro','Ray Arnold']],
    ['rex','¿Qué dinosaurio escapa durante la tormenta?','Tyrannosaurus rex',['Tyrannosaurus rex','Triceratops','Brachiosaurus','Dilophosaurus']],
    ['cocina','¿Qué dinosaurios persiguen a los chicos en la cocina?','Velociraptors',['Velociraptors','Compys','Gallimimus','Pteranodones']],
    ['frase','¿Quién dice “La vida se abre camino”?','Ian Malcolm',['Ian Malcolm','Alan Grant','John Hammond','Ellie Sattler']],
    ['chicos','¿Cómo se llaman los nietos de Hammond?','Tim y Lex',['Tim y Lex','Zach y Gray','Eric y Kelly','Billy y Sarah']],
    ['profesion','¿Cuál es la especialidad de Ellie Sattler?','Paleobotánica',['Paleobotánica','Genética','Veterinaria','Geología']]
  ]},
  { id: 'killbill', title: 'Kill Bill', year: 2003, genre: 'Acción', color: 'linear-gradient(145deg,#8d7324,#231d0c 78%)', facts: [
    ['novia','¿Quién interpreta a La Novia?','Uma Thurman',['Uma Thurman','Lucy Liu','Daryl Hannah','Vivica A. Fox']],
    ['director','¿Quién dirigió la película?','Quentin Tarantino',['Quentin Tarantino','Robert Rodriguez','Guy Ritchie','David Fincher']],
    ['nombre','¿Cuál es el verdadero nombre de La Novia?','Beatrix Kiddo',['Beatrix Kiddo','Elle Driver','O-Ren Ishii','Vernita Green']],
    ['espada','¿Quién fabrica la espada de Beatrix?','Hattori Hanzo',['Hattori Hanzo','Pai Mei','Bill','Budd']],
    ['traje','¿De qué color es el traje más icónico de Beatrix?','Amarillo',['Amarillo','Rojo','Negro','Blanco']],
    ['enemiga','¿Quién lidera a los 88 Maníacos?','O-Ren Ishii',['O-Ren Ishii','Elle Driver','Vernita Green','Sofie Fatale']],
    ['entrenador','¿Quién entrena a Beatrix en artes marciales?','Pai Mei',['Pai Mei','Hattori Hanzo','Johnny Mo','Bill']],
    ['coma','¿Cuántos años pasa Beatrix en coma?','Cuatro',['Cuatro','Dos','Cinco','Siete']],
    ['bill','¿Quién interpreta a Bill?','David Carradine',['David Carradine','Michael Madsen','Sonny Chiba','Michael Parks']],
    ['hija','¿Cómo se llama la hija de Beatrix?','B.B.',['B.B.','Nikki','Sofie','Elle']],
    ['grupo','¿Cómo se llama el grupo de asesinos de Bill?','Escuadrón Asesino Víbora Letal',['Escuadrón Asesino Víbora Letal','Los 88 Maníacos','La Mano Negra','Los Cinco Venenos']],
    ['lugar','¿En qué país consigue Beatrix su espada?','Japón',['Japón','China','Corea del Sur','Tailandia']]
  ]},
  { id: 'shrek', title: 'Shrek', year: 2001, genre: 'Animación', color: 'linear-gradient(145deg,#60793b,#182012 78%)', facts: [
    ['especie','¿Qué clase de criatura es Shrek?','Un ogro',['Un ogro','Un troll','Un gigante','Un duende']],
    ['hogar','¿Dónde vive Shrek?','En un pantano',['En un pantano','En un castillo','En una cueva','En un molino']],
    ['amigo','¿Qué animal acompaña a Shrek?','Un burro',['Un burro','Un caballo','Un gato','Un dragón']],
    ['princesa','¿Cómo se llama la princesa que rescata?','Fiona',['Fiona','Aurora','Farah','Ella']],
    ['villano','¿Quién gobierna Duloc?','Lord Farquaad',['Lord Farquaad','Príncipe Encantador','Rey Harold','Rumpelstiltskin']],
    ['maldicion','¿En qué se transforma Fiona por la noche?','En ogresa',['En ogresa','En dragón','En bruja','En loba']],
    ['voz','¿Quién hace la voz original de Shrek?','Mike Myers',['Mike Myers','Eddie Murphy','John Lithgow','Robin Williams']],
    ['burro','¿Quién hace la voz original de Burro?','Eddie Murphy',['Eddie Murphy','Chris Rock','Will Smith','Martin Lawrence']],
    ['actriz','¿Quién hace la voz original de Fiona?','Cameron Diaz',['Cameron Diaz','Drew Barrymore','Jennifer Aniston','Meg Ryan']],
    ['dragon','¿De quién se enamora la dragona?','De Burro',['De Burro','De Shrek','De Farquaad','Del Gato con Botas']],
    ['rescate','¿Dónde está encerrada Fiona?','En una torre',['En una torre','En un calabozo','En un barco','En un bosque']],
    ['cancion','¿Qué canción suena al comienzo?','All Star',['All Star','I’m a Believer','Hallelujah','Accidentally in Love']]
  ]},
  { id: 'godfather', title: 'El Padrino', year: 1972, genre: 'Drama', color: 'linear-gradient(145deg,#5b251d,#191113 78%)', facts: [
    ['familia','¿Qué familia protagoniza la historia?','Los Corleone',['Los Corleone','Los Barzini','Los Tattaglia','Los Soprano']],
    ['padrino','¿Quién interpreta a Vito Corleone?','Marlon Brando',['Marlon Brando','Al Pacino','Robert De Niro','James Caan']],
    ['hijo','¿Qué hijo termina al frente de la familia?','Michael',['Michael','Sonny','Fredo','Tom']],
    ['actor','¿Quién interpreta a Michael?','Al Pacino',['Al Pacino','Robert Duvall','James Caan','John Cazale']],
    ['director','¿Quién dirigió la película?','Francis Ford Coppola',['Francis Ford Coppola','Martin Scorsese','Brian De Palma','Sidney Lumet']],
    ['boda','¿Quién se casa al comienzo?','Connie',['Connie','Kay','Apollonia','Lucy']],
    ['consejero','¿Quién es el consigliere de la familia?','Tom Hagen',['Tom Hagen','Luca Brasi','Paulie Gatto','Carlo Rizzi']],
    ['sicilia','¿A dónde escapa Michael tras matar a Sollozzo?','Sicilia',['Sicilia','Cuba','Malta','Córcega']],
    ['caballo','¿Qué encuentra Jack Woltz en su cama?','La cabeza de su caballo',['La cabeza de su caballo','Un arma','Una carta','Dinero']],
    ['frase','¿Qué clase de oferta promete hacer Vito?','Una que no podrán rechazar',['Una que no podrán rechazar','Una muy generosa','Una única vez','Una por escrito']],
    ['negocio','¿Qué nuevo negocio rechaza Vito?','Narcotráfico',['Narcotráfico','Casinos','Alcohol','Apuestas']],
    ['esposa','¿Cómo se llama la novia y luego esposa de Michael?','Kay Adams',['Kay Adams','Connie Corleone','Apollonia Vitelli','Lucy Mancini']]
  ]},
  { id: 'lotr', title: 'El Señor de los Anillos', year: 2001, genre: 'Fantasía', color: 'linear-gradient(145deg,#564123,#1d1710 78%)', facts: [
    ['portador','¿Quién lleva el Anillo Único?','Frodo Bolsón',['Frodo Bolsón','Bilbo Bolsón','Sam Gamyi','Aragorn']],
    ['amigo','¿Quién acompaña a Frodo hasta el final?','Sam Gamyi',['Sam Gamyi','Merry','Pippin','Boromir']],
    ['destruccion','¿Dónde debe destruirse el Anillo?','Monte del Destino',['Monte del Destino','Minas Tirith','Rivendel','La Montaña Solitaria']],
    ['mago','¿Qué mago forma parte de la Comunidad?','Gandalf',['Gandalf','Saruman','Radagast','Alatar']],
    ['rey','¿Quién es el heredero al trono de Gondor?','Aragorn',['Aragorn','Boromir','Faramir','Théoden']],
    ['criatura','¿Quién llama al Anillo “mi tesoro”?','Gollum',['Gollum','Sauron','Smaug','Gríma']],
    ['elfo','¿Cómo se llama el arquero elfo?','Legolas',['Legolas','Elrond','Haldir','Celeborn']],
    ['enano','¿Cómo se llama el guerrero enano?','Gimli',['Gimli','Balin','Dwalin','Thorin']],
    ['villano','¿Quién creó el Anillo Único?','Sauron',['Sauron','Saruman','Morgoth','Isildur']],
    ['hogar','¿Dónde viven los hobbits?','La Comarca',['La Comarca','Rohan','Gondor','Lothlórien']],
    ['director','¿Quién dirigió la trilogía?','Peter Jackson',['Peter Jackson','George Lucas','Guillermo del Toro','Sam Raimi']],
    ['comunidad','¿Cuántos miembros tiene la Comunidad original?','Nueve',['Nueve','Siete','Ocho','Diez']]
  ]},
  { id: 'starwars', title: 'Star Wars', year: 1977, genre: 'Ciencia ficción', color: 'linear-gradient(145deg,#3d416a,#11131e 78%)', facts: [
    ['padre','¿Quién es el padre de Luke Skywalker?','Darth Vader',['Darth Vader','Obi-Wan Kenobi','Yoda','Palpatine']],
    ['hermana','¿Quién es la hermana de Luke?','Leia Organa',['Leia Organa','Padmé Amidala','Rey','Ahsoka Tano']],
    ['maestro','¿Qué pequeño maestro Jedi entrena a Luke?','Yoda',['Yoda','Qui-Gon Jinn','Mace Windu','Ki-Adi-Mundi']],
    ['piloto','¿Quién pilota el Halcón Milenario?','Han Solo',['Han Solo','Luke Skywalker','Lando Calrissian','Poe Dameron']],
    ['copiloto','¿Cómo se llama el copiloto wookiee?','Chewbacca',['Chewbacca','Wicket','Jabba','Greedo']],
    ['droide','¿Qué droide azul lleva los planos de la Estrella de la Muerte?','R2-D2',['R2-D2','C-3PO','BB-8','K-2SO']],
    ['arma','¿Qué arma usan los Jedi?','Sable de luz',['Sable de luz','Bláster sónico','Lanza de plasma','Espada láser doble']],
    ['imperio','¿Quién gobierna el Imperio?','Palpatine',['Palpatine','Tarkin','Darth Maul','Dooku']],
    ['planeta','¿En qué planeta crece Luke?','Tatooine',['Tatooine','Naboo','Alderaan','Coruscant']],
    ['princesa','¿Qué planeta natal de Leia es destruido?','Alderaan',['Alderaan','Hoth','Endor','Kashyyyk']],
    ['orden','¿Cómo se llama la orden de caballeros de la Fuerza?','Jedi',['Jedi','Sith','Mandalorianos','Clones']],
    ['creador','¿Quién creó la saga?','George Lucas',['George Lucas','Steven Spielberg','J. J. Abrams','Irvin Kershner']]
  ]},
  { id: 'avatar', title: 'Avatar', year: 2009, genre: 'Ciencia ficción', color: 'linear-gradient(145deg,#235f76,#101b25 78%)', facts: [
    ['planeta','¿Cómo se llama la luna donde viven los Na’vi?','Pandora',['Pandora','Endor','Arrakis','Krypton']],
    ['protagonista','¿Cómo se llama el protagonista?','Jake Sully',['Jake Sully','Miles Quaritch','Norm Spellman','Tommy Sully']],
    ['navi','¿Cómo se llama la guerrera Na’vi que ayuda a Jake?','Neytiri',['Neytiri','Mo’at','Grace','Trudy']],
    ['mineral','¿Qué mineral buscan los humanos?','Unobtanium',['Unobtanium','Vibranium','Adamantium','Kryptonite']],
    ['director','¿Quién dirigió Avatar?','James Cameron',['James Cameron','Peter Jackson','Ridley Scott','Denis Villeneuve']],
    ['actriz','¿Quién interpreta a la doctora Grace Augustine?','Sigourney Weaver',['Sigourney Weaver','Michelle Rodriguez','Kate Winslet','Zoe Saldaña']],
    ['conexion','¿Qué usan los Na’vi para conectarse con otras criaturas?','Su trenza neural',['Su trenza neural','Un amuleto','Una máscara','Un implante metálico']],
    ['diosa','¿Cómo se llama la deidad de Pandora?','Eywa',['Eywa','Gaia','Kiri','Toruk']],
    ['montura','¿Qué criatura voladora monta Jake?','Un ikran',['Un ikran','Un thanator','Un tulkun','Un hexápodo']],
    ['cuerpo','¿Qué controla Jake mientras su cuerpo humano duerme?','Un avatar Na’vi',['Un avatar Na’vi','Un robot','Un clon humano','Una nave']],
    ['corporacion','¿Qué sigla identifica a la organización humana?','RDA',['RDA','Weyland','NASA','UNSC']],
    ['coronel','¿Cómo se apellida el coronel antagonista?','Quaritch',['Quaritch','Sully','Selfridge','Tsu’tey']]
  ]},
  { id: 'wolf', title: 'El lobo de Wall Street', year: 2013, genre: 'Comedia', color: 'linear-gradient(145deg,#587246,#151b12 78%)', facts: [
    ['protagonista','¿Cómo se llama el corredor de bolsa protagonista?','Jordan Belfort',['Jordan Belfort','Donnie Azoff','Mark Hanna','Patrick Denham']],
    ['actor','¿Quién interpreta a Jordan Belfort?','Leonardo DiCaprio',['Leonardo DiCaprio','Matt Damon','Christian Bale','Bradley Cooper']],
    ['director','¿Quién dirigió la película?','Martin Scorsese',['Martin Scorsese','Oliver Stone','David Fincher','Adam McKay']],
    ['empresa','¿Cómo se llama la firma de Jordan?','Stratton Oakmont',['Stratton Oakmont','Belfort Capital','Wall Street Partners','Oakmont Brothers']],
    ['socio','¿Quién interpreta a Donnie Azoff?','Jonah Hill',['Jonah Hill','Seth Rogen','Miles Teller','Jesse Eisenberg']],
    ['ventas','¿Qué tipo de acciones venden principalmente?','Acciones de centavo',['Acciones de centavo','Bonos del tesoro','Criptomonedas','Acciones tecnológicas']],
    ['agente','¿Cómo se apellida el agente del FBI que investiga a Jordan?','Denham',['Denham','Coleman','Hanna','Madden']],
    ['yate','¿Cómo se llama el yate de Jordan?','Naomi',['Naomi','Nadine','Victoria','Duchess']],
    ['droga','¿Qué sedante causa la escena del Lamborghini?','Quaaludes',['Quaaludes','Morfina','Éxtasis','Ketamina']],
    ['esposa','¿Cómo se llama la segunda esposa de Jordan?','Naomi',['Naomi','Teresa','Emma','Molly']],
    ['pais','¿En qué país esconden dinero?','Suiza',['Suiza','Mónaco','Panamá','Luxemburgo']],
    ['hecho','¿La historia está basada en una persona real?','Sí',['Sí','No','Sólo el final','Sólo los personajes secundarios']]
  ]},
  { id: 'interstellar', title: 'Interestelar', year: 2014, genre: 'Ciencia ficción', color: 'linear-gradient(145deg,#352c65,#10131f 78%)', facts: [
    ['director','¿Quién dirigió la película?','Christopher Nolan',['Christopher Nolan','Denis Villeneuve','James Cameron','Ridley Scott']],
    ['piloto','¿Cómo se llama el piloto protagonista?','Cooper',['Cooper','Mann','Doyle','Romilly']],
    ['hija','¿Cómo se llama la hija de Cooper?','Murph',['Murph','Amelia','Lois','Jess']],
    ['robot','¿Cómo se llama el robot rectangular?','TARS',['TARS','HAL','CASEY','KIPP']],
    ['agujero','¿Qué fenómeno permite viajar a otra galaxia?','Un agujero de gusano',['Un agujero de gusano','Una supernova','Un púlsar','Un cometa']],
    ['planeta','¿Qué planeta visitan primero?','El de Miller',['El de Miller','El de Mann','El de Edmunds','Marte']],
    ['tiempo','¿Cuánto equivale una hora en el planeta de Miller?','Siete años en la Tierra',['Siete años en la Tierra','Un año en la Tierra','Veinticuatro horas','Cien años']],
    ['cientifica','¿Cómo se llama la científica interpretada por Anne Hathaway?','Amelia Brand',['Amelia Brand','Murph Cooper','Laura Miller','Lois Cooper']],
    ['agencia','¿Qué organización dirige la misión?','NASA',['NASA','ESA','ONU','SpaceX']],
    ['agujero-negro','¿Cómo se llama el agujero negro?','Gargantúa',['Gargantúa','Saturno','Lázaro','Endurance']],
    ['mensaje','¿Qué usa Cooper para comunicarse desde el teseracto?','La gravedad',['La gravedad','La luz','El sonido','La electricidad']],
    ['nave','¿Cómo se llama la nave principal?','Endurance',['Endurance','Ranger','Lazarus','Discovery']]
  ]},
  { id: 'shining', title: 'El resplandor', year: 1980, genre: 'Terror', color: 'linear-gradient(145deg,#763a3e,#1f1418 78%)', facts: [
    ['hotel','¿Cómo se llama el hotel?','Overlook',['Overlook','Bates','Stanley','Colorado Grand']],
    ['protagonista','¿Quién interpreta a Jack Torrance?','Jack Nicholson',['Jack Nicholson','Anthony Hopkins','Robert De Niro','Gene Hackman']],
    ['hijo','¿Cómo se llama el hijo de Jack?','Danny',['Danny','Tony','Dick','Lloyd']],
    ['poder','¿Qué habilidad posee Danny?','El resplandor',['El resplandor','Telequinesis','Invisibilidad','Viaje astral']],
    ['habitacion','¿Qué número tiene la habitación prohibida?','237',['237','217','13','101']],
    ['palabra','¿Qué palabra escribe Danny al revés?','REDRUM',['REDRUM','MURDERER','ESCAPE','OVERLOOK']],
    ['esposa','¿Quién interpreta a Wendy?','Shelley Duvall',['Shelley Duvall','Sissy Spacek','Mia Farrow','Jamie Lee Curtis']],
    ['laberinto','¿Dónde ocurre la persecución final?','En un laberinto de setos',['En un laberinto de setos','En el salón','En la cocina','En el bosque']],
    ['temporada','¿Durante qué estación queda aislada la familia?','Invierno',['Invierno','Verano','Otoño','Primavera']],
    ['gemelas','¿A quiénes ve Danny en los pasillos?','A dos gemelas',['A dos gemelas','A dos ancianos','A dos payasos','A dos monjas']],
    ['director','¿Quién dirigió la película?','Stanley Kubrick',['Stanley Kubrick','Alfred Hitchcock','John Carpenter','Roman Polanski']],
    ['autor','¿Quién escribió la novela original?','Stephen King',['Stephen King','Dean Koontz','Clive Barker','Edgar Allan Poe']]
  ]},
  { id: 'forrest', title: 'Forrest Gump', year: 1994, genre: 'Drama', color: 'linear-gradient(145deg,#496b86,#151d24 78%)', facts: [
    ['actor','¿Quién interpreta a Forrest?','Tom Hanks',['Tom Hanks','Robin Williams','Kevin Costner','John Travolta']],
    ['amor','¿Cómo se llama el gran amor de Forrest?','Jenny',['Jenny','Dorothy','Susan','Louise']],
    ['amigo','¿Cómo se llama su amigo del ejército?','Bubba',['Bubba','Dan','Elvis','Benjamin']],
    ['teniente','¿Qué teniente pierde las piernas?','Teniente Dan',['Teniente Dan','Teniente Mark','Teniente George','Teniente Mike']],
    ['negocio','¿Qué negocio funda Forrest?','Una empresa de camarones',['Una empresa de camarones','Una fábrica de chocolates','Una compañía de taxis','Un restaurante']],
    ['deporte','¿En qué deporte se destaca durante su recuperación?','Ping-pong',['Ping-pong','Tenis','Béisbol','Golf']],
    ['guerra','¿En qué guerra combate?','Vietnam',['Vietnam','Corea','Golfo Pérsico','Segunda Guerra Mundial']],
    ['frase','¿Con qué compara su madre a la vida?','Con una caja de bombones',['Con una caja de bombones','Con una carrera','Con un río','Con una pluma']],
    ['estado','¿En qué estado nació Forrest?','Alabama',['Alabama','Georgia','Texas','Luisiana']],
    ['carrera','¿Durante cuánto tiempo corre por el país?','Más de tres años',['Más de tres años','Seis meses','Un año','Diez años']],
    ['banco','¿Dónde cuenta gran parte de su historia?','En un banco de plaza',['En un banco de plaza','En un tren','En un hospital','En un bar']],
    ['director','¿Quién dirigió la película?','Robert Zemeckis',['Robert Zemeckis','Steven Spielberg','Ron Howard','Frank Darabont']]
  ]},
  { id: 'terminator2', title: 'Terminator 2', year: 1991, genre: 'Acción', color: 'linear-gradient(145deg,#48515b,#15191e 78%)', facts: [
    ['protector','¿Qué modelo de Terminator protege a John Connor?','T-800',['T-800','T-1000','T-X','Rev-9']],
    ['actor','¿Quién interpreta al T-800?','Arnold Schwarzenegger',['Arnold Schwarzenegger','Sylvester Stallone','Jean-Claude Van Damme','Dolph Lundgren']],
    ['enemigo','¿De qué material parece estar hecho el T-1000?','Metal líquido',['Metal líquido','Titanio','Acero sólido','Nanofibras']],
    ['joven','¿Cómo se llama el joven que deben proteger?','John Connor',['John Connor','Kyle Reese','Miles Dyson','Danny Dyson']],
    ['madre','¿Quién interpreta a Sarah Connor?','Linda Hamilton',['Linda Hamilton','Sigourney Weaver','Jamie Lee Curtis','Sharon Stone']],
    ['red','¿Cómo se llama la inteligencia artificial?','Skynet',['Skynet','Cybernet','Omnius','Genesis']],
    ['empresa','¿Qué empresa desarrolla la tecnología?','Cyberdyne Systems',['Cyberdyne Systems','Weyland Industries','Tyrell Corporation','Omni Consumer Products']],
    ['cientifico','¿Qué ingeniero trabaja en el futuro de Skynet?','Miles Dyson',['Miles Dyson','John Connor','Todd Voight','Peter Silberman']],
    ['frase','¿Qué frase aprende el T-800 de John?','Hasta la vista, baby',['Hasta la vista, baby','Volveré pronto','Sayonara','Nos vemos, amigo']],
    ['vehiculo','¿Qué conduce el T-800 al salir del bar?','Una motocicleta',['Una motocicleta','Un camión','Un deportivo','Un helicóptero']],
    ['final','¿Qué gesto hace el T-800 al hundirse?','Levanta el pulgar',['Levanta el pulgar','Hace la V','Saluda','Cierra el puño']],
    ['director','¿Quién dirigió la película?','James Cameron',['James Cameron','Paul Verhoeven','John McTiernan','Ridley Scott']]
  ]},
  { id: 'endgame', title: 'Avengers: Endgame', year: 2019, genre: 'Acción', color: 'linear-gradient(145deg,#5b3f78,#1a1323 78%)', facts: [
    ['villano','¿Quién eliminó a la mitad del universo?','Thanos',['Thanos','Ultron','Loki','Ronan']],
    ['sacrificio','¿Quién se sacrifica usando las Gemas del Infinito?','Tony Stark',['Tony Stark','Steve Rogers','Thor','Bruce Banner']],
    ['vormir','¿Quién muere en Vormir?','Natasha Romanoff',['Natasha Romanoff','Wanda Maximoff','Nebula','Gamora']],
    ['martillo','¿Quién logra empuñar Mjolnir durante la batalla?','Capitán América',['Capitán América','Hawkeye','Ant-Man','War Machine']],
    ['viaje','¿Qué plan usan para recuperar las Gemas?','Viajar en el tiempo',['Viajar en el tiempo','Invadir Titán','Crear nuevas Gemas','Destruir el Guantelete']],
    ['reino','¿Qué lugar permite el viaje temporal?','El Reino Cuántico',['El Reino Cuántico','La Zona Negativa','Asgard','La Dimensión Oscura']],
    ['chasquido','¿Quién hace el primer chasquido para traer a todos de vuelta?','Hulk',['Hulk','Thor','Iron Man','Capitán América']],
    ['antman','¿Quién regresa después de quedar atrapado cinco años?','Ant-Man',['Ant-Man','Doctor Strange','Spider-Man','Black Panther']],
    ['frase','¿Quién escucha “A tu izquierda” antes de los portales?','Capitán América',['Capitán América','Iron Man','Thor','Hawkeye']],
    ['retiro','¿Qué héroe vuelve anciano después de devolver las Gemas?','Steve Rogers',['Steve Rogers','Bruce Banner','Clint Barton','Scott Lang']],
    ['directores','¿Quiénes dirigieron la película?','Anthony y Joe Russo',['Anthony y Joe Russo','Joel y Ethan Coen','Lana y Lilly Wachowski','Peter y Bobby Farrelly']],
    ['año','¿Cuántos años pasan después del chasquido de Thanos?','Cinco',['Cinco','Tres','Siete','Diez']]
  ]},
  { id: 'pirates', title: 'Piratas del Caribe', year: 2003, genre: 'Aventura', color: 'linear-gradient(145deg,#625337,#1b1812 78%)', facts: [
    ['capitan','¿Cómo se llama el capitán interpretado por Johnny Depp?','Jack Sparrow',['Jack Sparrow','Héctor Barbossa','Will Turner','Davy Jones']],
    ['barco','¿Cómo se llama el barco de Jack Sparrow?','Perla Negra',['Perla Negra','Holandés Errante','Interceptor','Venganza de la Reina Ana']],
    ['herrero','¿Cuál es el oficio de Will Turner al comienzo?','Herrero',['Herrero','Marinero','Soldado','Carpintero']],
    ['actriz','¿Quién interpreta a Elizabeth Swann?','Keira Knightley',['Keira Knightley','Natalie Portman','Kate Winslet','Rachel Weisz']],
    ['enemigo','¿Quién es el capitán maldito de la primera película?','Héctor Barbossa',['Héctor Barbossa','Davy Jones','Barbanegra','Cutler Beckett']],
    ['maldicion','¿En qué se convierten los piratas bajo la luz de la luna?','En esqueletos',['En esqueletos','En fantasmas','En peces','En piedra']],
    ['moneda','¿Qué deben devolver para romper la maldición?','Monedas aztecas',['Monedas aztecas','Un medallón inglés','Una brújula','Una corona']],
    ['brujula','¿Qué indica la brújula de Jack?','Lo que más desea quien la sostiene',['El norte','El tesoro más cercano','El rumbo del Perla Negra','Lo que más desea quien la sostiene']],
    ['villano2','¿Quién tiene tentáculos en la cara?','Davy Jones',['Davy Jones','Barbossa','Barbanegra','Bootstrap Bill']],
    ['barco2','¿Qué barco capitanea Davy Jones?','Holandés Errante',['Holandés Errante','Perla Negra','Interceptor','Dauntless']],
    ['lugar','¿En qué puerto vive Elizabeth?','Port Royal',['Port Royal','Tortuga','Nassau','Singapur']],
    ['bebida','¿Cuál es la bebida favorita de Jack?','Ron',['Ron','Whisky','Vino','Cerveza']]
  ]},
  { id: 'fastfive', title: 'Rápidos y Furiosos 5', year: 2011, genre: 'Acción', color: 'linear-gradient(145deg,#5b5d67,#18191e 78%)', facts: [
    ['ciudad','¿En qué ciudad ocurre el gran golpe?','Río de Janeiro',['Río de Janeiro','Miami','Los Ángeles','Tokio']],
    ['dom','¿Quién interpreta a Dominic Toretto?','Vin Diesel',['Vin Diesel','Paul Walker','Dwayne Johnson','Jason Statham']],
    ['brian','¿Quién interpreta a Brian O’Conner?','Paul Walker',['Paul Walker','Vin Diesel','Tyrese Gibson','Ludacris']],
    ['agente','¿Cómo se llama el agente interpretado por Dwayne Johnson?','Luke Hobbs',['Luke Hobbs','Deckard Shaw','Roman Pearce','Vince']],
    ['objetivo','¿Qué arrastra el equipo por las calles durante el golpe final?','Una bóveda',['Una bóveda','Un camión cisterna','Un tren','Un contenedor']],
    ['villano','¿Cómo se apellida el empresario criminal?','Reyes',['Reyes','Braga','Tran','Shaw']],
    ['inicio','¿Qué vehículo asaltan al comienzo?','Un tren',['Un tren','Un avión','Un barco','Un camión']],
    ['mecanico','¿Quién es el experto informático del equipo?','Tej',['Tej','Roman','Han','Vince']],
    ['comico','¿Quién suele bromear y discutir con Tej?','Roman',['Roman','Han','Dom','Hobbs']],
    ['pareja','¿Con quién mantiene una relación Han?','Gisele',['Gisele','Mia','Elena','Letty']],
    ['familia','¿Cómo se llama la hermana de Dom?','Mia',['Mia','Letty','Elena','Monica']],
    ['director','¿Quién dirigió la película?','Justin Lin',['Justin Lin','James Wan','Rob Cohen','John Singleton']]
  ]},
  { id: 'nuevereinas', title: 'Nueve Reinas', year: 2000, genre: 'Crimen', color: 'linear-gradient(145deg,#6e5838,#1c1812 78%)', facts: [
    ['marcos','¿Quién interpreta a Marcos?','Ricardo Darín',['Ricardo Darín','Gastón Pauls','Diego Peretti','Guillermo Francella']],
    ['juan','¿Quién interpreta a Juan?','Gastón Pauls',['Gastón Pauls','Ricardo Darín','Pablo Echarri','Leonardo Sbaraglia']],
    ['objeto','¿Qué son las Nueve Reinas?','Una colección de estampillas',['Una colección de estampillas','Nueve monedas','Un mazo de cartas','Nueve pinturas']],
    ['director','¿Quién dirigió la película?','Fabián Bielinsky',['Fabián Bielinsky','Juan José Campanella','Damián Szifron','Pablo Trapero']],
    ['ciudad','¿En qué ciudad transcurre la historia?','Buenos Aires',['Buenos Aires','Rosario','Montevideo','Córdoba']],
    ['genero','¿Qué tipo de delincuentes son Marcos y Juan?','Estafadores',['Estafadores','Ladrones de bancos','Contrabandistas','Detectives corruptos']],
    ['encuentro','¿Dónde conoce Marcos a Juan?','En una estación de servicio',['En una estación de servicio','En un banco','En un hotel','En un casino']],
    ['hermana','¿Cómo se llama la hermana de Marcos?','Valeria',['Valeria','Laura','Cecilia','Victoria']],
    ['actriz','¿Quién interpreta a Valeria?','Leticia Brédice',['Leticia Brédice','Cecilia Roth','Mercedes Morán','Érica Rivas']],
    ['comprador','¿Dónde se aloja el posible comprador de las estampillas?','En un hotel',['En un hotel','En una embajada','En un crucero','En una estancia']],
    ['banco','¿Qué ocurre con el banco donde Marcos deposita el dinero?','Quiebra',['Quiebra','Es asaltado','Se incendia','Congela sólo su cuenta']],
    ['pais','¿De qué país es la película?','Argentina',['Argentina','España','Uruguay','México']]
  ]}
];
